services:
  db:
    image: postgres:latest
    container_name: workshop-postgres
    environment:
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: workshop
      POSTGRES_DB: workshop_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "workshop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
